# Generated by Django 4.2.6 on 2023-10-13 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('content', models.TextField()),
                ('type', models.CharField(choices=[('BoardingPass', 'BoardingPass'), ('Invoice', 'Invoice'), ('Advertisement', 'Advertisement')], max_length=50, unique=True)),
                ('active', models.BooleanField(default=False)),
            ],
        ),
    ]
