# Generated by Django 4.2.6 on 2023-10-13 15:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(blank=True, max_length=20, unique=True)),
                ('issue_date', models.DateField()),
                ('due_date', models.DateField()),
                ('products_or_services', models.TextField()),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tax', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='invoices_received', to='api.template')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Invoice',
                'verbose_name_plural': 'Invoices',
            },
        ),
        migrations.CreateModel(
            name='GeneratedBoardingPass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_data', models.BinaryField()),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('passenger_name', models.CharField(max_length=255)),
                ('seat_number', models.CharField(max_length=10)),
                ('departure_date', models.DateTimeField()),
                ('boarding_gate', models.CharField(max_length=10)),
                ('template', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='generated_boarding_passes', to='api.template')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_posted', models.DateTimeField()),
                ('place', models.CharField(max_length=100)),
                ('location', models.CharField(choices=[('LIGHT_BOXES', 'Light Boxes'), ('TENSION_FABRIC', 'Tension Fabric'), ('ADHESIVE_VINYL', 'Adhesive Vinyl'), ('VIDEO_WALL_OR_SCREENS', 'Video Wall or Screens'), ('BACK_COVER', 'Back Cover'), ('LUGGAGE_CART', 'Luggage Cart'), ('INTERACTIVE_POP_UPS', 'Interactive / Pop-Ups'), ('COLUMNS', 'Columns')], max_length=50, unique=True)),
                ('template', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='Advertisement', to='api.template')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
