# Generated by Django 4.2.6 on 2023-10-13 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_invoice_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='template',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Advertisement', to='api.template'),
        ),
        migrations.AlterField(
            model_name='generatedboardingpass',
            name='template',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='generated_boarding_passes', to='api.template'),
        ),
    ]
