# Generated by Django 4.2.6 on 2023-10-15 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_advertisement_name_generatedboardingpass_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisement',
            name='location',
        ),
    ]
